"""
Tests that the hand-written OpenAPI spec stays in sync with the actual API.

Compares docs/architecture/api_specification.yaml against the schema
auto-generated by FastAPI from src/api/main.py + src/api/schemas.py.

If this test fails, update the YAML spec to match the code (or vice versa).
"""

from pathlib import Path

import pytest
import yaml

from src.api.main import app

SPEC_PATH = Path(__file__).resolve().parents[1] / "docs" / "architecture" / "api_specification.yaml"


@pytest.fixture(scope="module")
def hand_written_spec() -> dict:
    """Load the hand-written OpenAPI YAML spec."""
    return yaml.safe_load(SPEC_PATH.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def generated_spec() -> dict:
    """Get the OpenAPI spec auto-generated by FastAPI."""
    return app.openapi()


class TestOpenAPIDrift:
    """Ensure hand-written spec does not drift from the actual API."""

    def test_spec_file_exists(self):
        assert SPEC_PATH.exists(), f"OpenAPI spec not found at {SPEC_PATH}"

    def test_paths_match(self, hand_written_spec, generated_spec):
        """Every route in the code must appear in the spec and vice versa."""
        spec_paths = set(hand_written_spec["paths"].keys())
        code_paths = set(generated_spec["paths"].keys())

        missing_from_spec = code_paths - spec_paths
        extra_in_spec = spec_paths - code_paths

        assert not missing_from_spec, (
            f"Endpoints in code but missing from spec: {missing_from_spec}"
        )
        assert not extra_in_spec, (
            f"Endpoints in spec but not in code: {extra_in_spec}"
        )

    def test_http_methods_match(self, hand_written_spec, generated_spec):
        """Each path must expose the same HTTP methods."""
        for path in generated_spec["paths"]:
            if path not in hand_written_spec["paths"]:
                continue  # caught by test_paths_match
            code_methods = set(generated_spec["paths"][path].keys())
            spec_methods = set(hand_written_spec["paths"][path].keys())
            assert code_methods == spec_methods, (
                f"{path}: methods differ — code={code_methods}, spec={spec_methods}"
            )

    def test_response_model_fields_match(self, hand_written_spec, generated_spec):
        """For endpoints with a response_model, check that required fields align."""
        gen_schemas = generated_spec.get("components", {}).get("schemas", {})
        spec_schemas = hand_written_spec.get("components", {}).get("schemas", {})

        # Only check schemas that exist in both
        shared = set(gen_schemas.keys()) & set(spec_schemas.keys())
        mismatches = []

        for name in shared:
            gen_required = set(gen_schemas[name].get("required", []))
            spec_required = set(spec_schemas[name].get("required", []))
            gen_props = set(gen_schemas[name].get("properties", {}).keys())
            spec_props = set(spec_schemas[name].get("properties", {}).keys())

            if gen_required != spec_required:
                mismatches.append(
                    f"{name}: required fields differ — "
                    f"code={sorted(gen_required)}, spec={sorted(spec_required)}"
                )
            if gen_props != spec_props:
                mismatches.append(
                    f"{name}: properties differ — "
                    f"code={sorted(gen_props)}, spec={sorted(spec_props)}"
                )

        assert not mismatches, (
            "Schema drift detected:\n" + "\n".join(mismatches)
        )

    def test_path_parameters_match(self, hand_written_spec, generated_spec):
        """Path parameters in the spec must match the code."""
        for path in generated_spec["paths"]:
            if path not in hand_written_spec["paths"]:
                continue
            for method in generated_spec["paths"][path]:
                code_op = generated_spec["paths"][path][method]
                spec_op = hand_written_spec["paths"][path].get(method, {})

                code_params = {
                    p["name"]
                    for p in code_op.get("parameters", [])
                    if p["in"] == "path"
                }
                spec_params = {
                    p["name"]
                    for p in spec_op.get("parameters", [])
                    if p["in"] == "path"
                }
                assert code_params == spec_params, (
                    f"{method.upper()} {path}: path params differ — "
                    f"code={code_params}, spec={spec_params}"
                )

    def test_no_phantom_query_params(self, hand_written_spec, generated_spec):
        """Spec must not declare query params that the code doesn't accept."""
        for path in hand_written_spec["paths"]:
            if path not in generated_spec["paths"]:
                continue
            for method in hand_written_spec["paths"][path]:
                spec_op = hand_written_spec["paths"][path][method]
                code_op = generated_spec["paths"][path].get(method, {})

                code_query = {
                    p["name"]
                    for p in code_op.get("parameters", [])
                    if p["in"] == "query"
                }
                spec_query = {
                    p["name"]
                    for p in spec_op.get("parameters", [])
                    if p["in"] == "query"
                }
                phantom = spec_query - code_query
                assert not phantom, (
                    f"{method.upper()} {path}: spec has phantom query params: {phantom}"
                )
