"""
PDF portfolio report generator.

Produces a single-page (or multi-page) PDF summarizing portfolio
optimization results: weights, metrics, top holdings, and alerts.

Requires: fpdf2 (optional dependency, `pip install fpdf2`)

Output: data/output/portfolio_report.pdf (or custom path)
"""

import logging
from pathlib import Path
from typing import Any

from src.storage import Storage, get_storage
from src.storage.base import StorageError

logger = logging.getLogger(__name__)

DEFAULT_OUTPUT_PATH = Path("data/output/portfolio_report.pdf")


class PDFExportError(Exception):
    """Error during PDF generation."""

    def __init__(self, message: str, *, operation: str = "pdf_export") -> None:
        self.message = message
        self.operation = operation
        super().__init__(message)


def _load_portfolio_data(
    storage: Storage,
    portfolio_key: str = "weights",
) -> dict[str, Any]:
    """Load portfolio data from storage."""
    try:
        return storage.load_output(portfolio_key)
    except (StorageError, FileNotFoundError) as e:
        raise PDFExportError(
            f"Portfolio not found (key={portfolio_key})",
            operation="load",
        ) from e


def generate_portfolio_report(
    output_path: str | Path | None = None,
    portfolio_key: str = "weights",
    title: str = "Portfolio Optimization Report",
    storage: Storage | None = None,
) -> dict[str, Any]:
    """
    Generate a PDF report of portfolio optimization results.

    Args:
        output_path: Output file path. Defaults to data/output/portfolio_report.pdf.
        portfolio_key: Storage key for portfolio ("weights" or "weights_trad").
        title: Report title.
        storage: Storage instance. If None, resolves from config.

    Returns:
        Dictionary with output path and report metadata.

    Raises:
        PDFExportError: If portfolio data is missing or PDF generation fails.
    """
    try:
        from fpdf import FPDF
    except ImportError as e:
        raise PDFExportError(
            "fpdf2 not installed. Run: pip install fpdf2",
            operation="import",
        ) from e

    if storage is None:
        storage = get_storage()

    if output_path is None:
        output_path = DEFAULT_OUTPUT_PATH
    output_path = Path(output_path)

    # Load data
    portfolio = _load_portfolio_data(storage, portfolio_key)
    weights = portfolio.get("weights", {})
    expected_return = portfolio.get("expected_return", 0.0)
    volatility = portfolio.get("volatility", 0.0)
    sharpe = portfolio.get("sharpe_ratio", 0.0)

    # Build PDF
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # Portfolio type
    label = "Traditional Assets" if portfolio_key == "weights_trad" else "Crypto Assets"
    pdf.set_font("Helvetica", "I", 11)
    pdf.cell(0, 8, f"Portfolio: {label}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(8)

    # KPI summary
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Key Metrics", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Expected Return: {expected_return:.2%}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Volatility: {volatility:.2%}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Sharpe Ratio: {sharpe:.4f}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Number of Assets: {len(weights)}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Weights table
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Portfolio Allocation", new_x="LMARGIN", new_y="NEXT")

    # Table header
    pdf.set_font("Helvetica", "B", 10)
    col_w = [60, 40, 40, 50]
    pdf.cell(col_w[0], 8, "Symbol", border=1)
    pdf.cell(col_w[1], 8, "Weight", border=1, align="R")
    pdf.cell(col_w[2], 8, "Weight %", border=1, align="R")
    pdf.cell(col_w[3], 8, "Rank", border=1, align="C")
    pdf.ln()

    # Table rows — sorted by weight descending
    pdf.set_font("Helvetica", "", 10)
    sorted_weights = sorted(weights.items(), key=lambda x: x[1], reverse=True)
    for rank, (symbol, weight) in enumerate(sorted_weights, 1):
        pdf.cell(col_w[0], 7, symbol, border=1)
        pdf.cell(col_w[1], 7, f"{weight:.6f}", border=1, align="R")
        pdf.cell(col_w[2], 7, f"{weight:.2%}", border=1, align="R")
        pdf.cell(col_w[3], 7, f"#{rank}", border=1, align="C")
        pdf.ln()

    pdf.ln(8)

    # Footer
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 6,
        "Generated by Portfolio Optimization Platform",
        new_x="LMARGIN", new_y="NEXT", align="C",
    )

    # Save
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(output_path))

    result = {
        "output_path": str(output_path),
        "portfolio_key": portfolio_key,
        "n_assets": len(weights),
        "title": title,
        "sharpe_ratio": sharpe,
    }

    logger.info("PDF report generated: %s (%d assets)", output_path, len(weights))
    return result
